AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test-helloworld

  Sample SAM Template for sam-test-helloworld

Globals:
  Function:
    Timeout: 600
    MemorySize: 128

Resources:
  LongTestHelloWorldFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LongTestHelloWorldFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LongTestSam_S3Permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: 
                  - arn:aws:s3:::ebics-test-bucket/*      
              - Effect: Allow
                Action: s3:ListBucket
                Resource: arn:aws:s3:::ebics-test-bucket
                Condition:
                  StringLike:
                    s3:prefix:
                    - "*"
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: !GetAtt LongTestHelloWorldFunctionRole.Arn
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  LongTestHelloWorldFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LongTestHelloWorldFunctionRole.Arn

